PropertyS3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.PropertyS3Bucket.name}

PropertyS3BucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref PropertyS3Bucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: "*"
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.PropertyS3Bucket.name}/*
