PropertiesTable:
  Type: "AWS::DynamoDB::Table"
  Properties:
    TableName: Properties-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PropertyId
        AttributeType: S
      - AttributeName: Location
        AttributeType: S
      - AttributeName: Status
        AttributeType: S
      - AttributeName: OwnerId
        AttributeType: S
    KeySchema:
      - AttributeName: PropertyId
        KeyType: HASH # Partition key
      - AttributeName: Location
        KeyType: RANGE # Sort key
    GlobalSecondaryIndexes:
      - IndexName: LocationIndex
        KeySchema:
          - AttributeName: Location
            KeyType: HASH
          - AttributeName: Status
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: OwnerIndex
        KeySchema:
          - AttributeName: OwnerId
            KeyType: HASH
        Projection:
          ProjectionType: ALL